### ISSUE TITLE
charms with layer-snap broken on s390x

### ISSUE THREAD

**Issue by Cynerva** [stub42/layer-snap#13]
```
2018-04-12 13:52:11 DEBUG install Traceback (most recent call last):
2018-04-12 13:52:11 DEBUG install   File "/var/lib/juju/agents/unit-etcd-0/charm/hooks/install", line 19, in <module>
2018-04-12 13:52:11 DEBUG install     main()
2018-04-12 13:52:11 DEBUG install   File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 71, in main
2018-04-12 13:52:11 DEBUG install     hookenv._run_atstart()
2018-04-12 13:52:11 DEBUG install   File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.5/site-packages/charmhelpers/core/hookenv.py", line 1090, in _run_atstart
2018-04-12 13:52:11 DEBUG install     callback(*args, **kwargs)
2018-04-12 13:52:11 DEBUG install   File "/var/lib/juju/agents/unit-etcd-0/charm/reactive/snap.py", line 239, in configure_snap_enterprise_proxy
2018-04-12 13:52:11 DEBUG install     ensure_snapd_min_version('2.30')
2018-04-12 13:52:11 DEBUG install   File "/var/lib/juju/agents/unit-etcd-0/charm/reactive/snap.py", line 211, in ensure_snapd_min_version
2018-04-12 13:52:11 DEBUG install     add_source('distro-proposed', fail_invalid=True)
2018-04-12 13:52:11 DEBUG install   File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.5/site-packages/charmhelpers/fetch/ubuntu.py", line 390, in add_source
2018-04-12 13:52:11 DEBUG install     fn(*m.groups())
2018-04-12 13:52:11 DEBUG install   File "/var/lib/juju/agents/unit-etcd-0/.venv/lib/python3.5/site-packages/charmhelpers/fetch/ubuntu.py", line 418, in _add_proposed
2018-04-12 13:52:11 DEBUG install     .format(arch))
2018-04-12 13:52:11 DEBUG install charmhelpers.fetch.SourceConfigError: Arch s390x not supported for (distro-)proposed
2018-04-12 13:52:11 ERROR juju.worker.uniter.operation runhook.go:113 hook "install" failed: exit status 1
```

Seems this was introduced by a recent change: https://github.com/stub42/layer-snap/commit/7e95f1b4bdc22b3613d90239084d35e2f6a897d1

A PR was merged to charmhelpers yesterday that should make this work: https://github.com/juju/charm-helpers/pull/150, however, it has not been released yet.

**Comment by johnsca** [comment]
charm-helpers 0.18.8 has been released with this fix.

**Comment by Cynerva** [comment]
Thanks @johnsca. I've just verified that newly built charms now work on s390x. Closing this.
